language: objective-c
osx_image: xcode8.3
xcode_workspace: chainbuilder.xcworkspace
xcode_scheme: AllTests
xcode_sdk: iphonesimulator10.3

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator10.3 -workspace chainbuilder.xcworkspace -scheme AllTests CODE_SIGNING_REQUIRED=NO && xcodebuild test -sdk iphonesimulator10.3 -workspace chainbuilder.xcworkspace -scheme AllTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'

