language: objective-c
osx_image: xcode9.2
xcode_workspace: chainbuilder.xcworkspace
xcode_scheme: AllTests
xcode_sdk: iphonesimulator11.2

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.2 -workspace chainbuilder.xcworkspace -scheme AllTests CODE_SIGNING_REQUIRED=NO && xcodebuild test -sdk iphonesimulator11.2 -workspace chainbuilder.xcworkspace -scheme AllTests -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2'

